version: "3"

services:
  bot:
    container_name: receipt-bot
    image: receipt-bot
    build: .
    restart: unless-stopped
    env_file: .secrets
    environment:
      - DB_URI=mongodb://db:27017
      - DB_NAME=receipt
      - DB_COLLECTION=receipts
  db:
    image: mongo:4.4.14
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
      - ./raw_data:/raw_data
    ports:
      - 27017:27017
    restart: unless-stopped
